### ISSUE TITLE
Deprecate kOfxParamHostPropSupportsBooleanAnimation

### ISSUE THREAD

**Issue by revisionfx** [AcademySoftwareFoundation/openfx#159]
As part of skimming too many options...

Deprecate: kOfxParamHostPropSupportsBooleanAnimation

Since every hosts now support this (to my knowledge)
We should move this to oldOFX,h
This then does not break anyone (including old host version and old plugins)...

**Comment by garyo** [comment]
Pierre says this can be closed.
